# Generated by Django 5.1 on 2024-08-29 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
