# Generated by Django 5.1 on 2025-01-11 01:14

from django.db import migrations, models
import random


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0002_order_order_number'),
    ]
    
    def generate_unique_order_numbers(apps, schema_editor):
        Order = apps.get_model('brew', 'Order')
        for order in Order.objects.all():
            while True:
                order_number = f"{random.randint(10000, 99999)}"
                if not Order.objects.filter(order_number=order_number).exists():
                    order.order_number = order_number
                    order.save()
                    break

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=5, unique=True, blank=True, null=True),
        ),
        migrations.RunPython(generate_unique_order_numbers),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
