# Generated by Django 5.1 on 2025-01-11 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0004_alter_order_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_number',
        ),
    ]
