# Generated by Django 5.1 on 2024-09-02 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0004_alter_coffee_price_alter_snack_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='caffeine_amount',
            field=models.IntegerField(),
        ),
    ]
