# Generated by Django 5.1 on 2024-09-05 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0006_alter_coffee_price_alter_snack_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffee',
            name='coffee_type',
        ),
        migrations.AddField(
            model_name='coffee',
            name='coffee_name',
            field=models.CharField(default='Default Description', max_length=200),
        ),
        migrations.AddField(
            model_name='coffee',
            name='description',
            field=models.CharField(default='Default Description', max_length=200),
        ),
        migrations.AddField(
            model_name='coffee',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='snack',
            name='description',
            field=models.CharField(default='Default Description', max_length=200),
        ),
        migrations.AddField(
            model_name='snack',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
    ]
