# Generated by Django 5.1 on 2024-09-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brew', '0007_remove_coffee_coffee_type_coffee_coffee_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='Default Description', max_length=200)),
                ('temperature', models.CharField(blank=True, max_length=500, null=True)),
                ('caffeine_amount', models.IntegerField(blank=True, null=True)),
                ('price', models.FloatField()),
                ('description', models.CharField(default='Default Description', max_length=200)),
                ('in_stock', models.BooleanField(default=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Coffee',
        ),
        migrations.DeleteModel(
            name='Snack',
        ),
    ]
