name: Validate OpenAPI Spec

on: 
    push:
      branches: ["main"]
      paths:
        - "**.yaml"
        - "**.yml"

jobs:
  specgate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install SpecGate
        run: go install github.com/itsdeannat/specgate@0.1.0

      - name: Check OpenAPI spec
        run: specgate check schema.yml
